version: '3.8'
services:
  wallet-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet_db
      - SPRING_DATASOURCE_USERNAME=walletuser
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - wallet-net

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=wallet_db
      - POSTGRES_USER=walletuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wallet-net

networks:
  wallet-net:
    driver: bridge

volumes:
  pgdata: